namespace OficinaMecanica.Application.Administrativo.ServicoCatalogoUseCases.ConsultarTempoMedioExecucaoServico;

public sealed record ConsultarTempoMedioExecucaoServicoRequest(Guid ServicoCatalogoId);
