apiVersion: v1
kind: Secret
metadata:
  name: oficina-mecanica-api-secret
  namespace: oficina-mecanica
type: Opaque
stringData:
  Jwt__Secret: oficina-mecanica-jwt-secret-local-2026
  Integracoes__Orcamento__WebhookToken: oficina-mecanica-orcamento-webhook-local-2026

  ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=OficinaMecanicaDb;User Id=sa;Password=OficinaMecanicaDbLocal@2026;TrustServerCertificate=True;"
