apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-mecanica-api-config
  namespace: oficina-mecanica
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Database__ApplyMigrationsOnStartup: "true"
  Database__SeedDemoData: "true"