apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-api
  namespace: oficina

spec:
  replicas: 1

  selector:
    matchLabels:
      app: oficina-api

  template:
    metadata:
      labels:
        app: oficina-api

    spec:
      containers:
        - name: oficina-api
          image: gbsousadev/oficina-api:1.0
          imagePullPolicy: Always

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          envFrom:
            - configMapRef:
                name: oficina-api-config

          ports:
            - containerPort: 8080

          startupProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          env:
            - name: Jwt__Secret
              valueFrom:
                secretKeyRef:
                  name: oficina-api-secret
                  key: Jwt__Secret

            - name: Integracoes__Orcamento__WebhookToken
              valueFrom:
                secretKeyRef:
                  name: oficina-api-secret
                  key: Integracoes__Orcamento__WebhookToken

            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: oficina-api-secret
                  key: ConnectionStrings__DefaultConnection