using OficinaMecanica.Domain.GestaoOrdemServico.Enums;

namespace OficinaMecanica.Application.GestaoOrdemServico.OrdemServicoUseCases.NotificarDecisaoOrcamento;

public sealed record NotificarDecisaoOrcamentoRequest(Guid OrdemServicoId, DecisaoOrcamento Decisao);
