apiVersion: v1
kind: Service

metadata:
  name: oficina-api
  namespace: oficina

spec:
  # AWS Academy: LoadBalancer cria recurso cobrado. Remover com terraform destroy
  # ao finalizar a demonstracao.
  type: LoadBalancer

  selector:
    app: oficina-api

  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
