namespace OficinaMecanica.Application.GestaoOrdemServico.OrdemServicoUseCases.ConsultarTempoMedioExecucaoServico;

public sealed record ConsultarTempoMedioExecucaoServicoRequest(Guid ServicoCatalogoId);
