namespace OficinaMecanica.Application.GestaoOrdemServico.OrdemServicoUseCases.DefinirServicos;

public sealed record DefinirServicosRequest(Guid OrdemServicoId, IReadOnlyCollection<Guid> ServicosCatalogoIds);
