using OficinaMecanica.Domain.GestaoOrdemServico.Enums;

namespace OficinaMecanica.Application.GestaoOrdemServico.OrdemServicoUseCases.CancelarOrdemServico;

public sealed record CancelarOrdemServicoRequest(Guid OrdemServicoId, MotivoCancelamentoOrdemServico Motivo);
